### PR TITLE
Fix CI job following molecule changes

### PR DESCRIPTION
**Pull request by marknet15**
A followup PR  to https://github.com/hannseman/ansible-homebridge/pull/4 to fix the CI due to a molecule upstream change
```
CRITICAL Failed to pre-validate.
{'driver': [{'name': ['unallowed value docker']}], 'lint': ['must be of string type']}
The command "molecule --debug test" exited with 1.
```
Think it's the same issue as reported here:
ansible-community/molecule#2891

### CODE REVIEW

**Comment by hannseman** [comment]
Thanks! Looks like it fixed one of the errors. 

The remaining one is 
`{'lint': ['must be of string type']} `

See the logs here:
https://travis-ci.com/github/hannseman/ansible-homebridge/builds/211034764

Related issue:

https://github.com/IBM/ibm-spectrum-scale-csi/issues/109

I think we want this on `provisioner`
```
lint: |
  set -e
  ansible-lint
```

And this on `verifier`
```
lint: |
  set -e
  flake8
```

**Comment by marknet15** [comment]
Thanks yeah I was on the same lines as yourself I think, I'm not that familiar with molecule so think I'll need to tweak what I just committed to what you have shown

**Comment by hannseman** [comment]
Ah looks like they removed `lint` on verifiers and provisioners. It should be top-level now.

See:
https://molecule.readthedocs.io/en/latest/configuration.html#lint

I think running ansible-lint is good enough. So remove lint from provisioners and verifiers and drop this in the toplevel of the molecule file:
```

lint: |
  set -e
  ansible-lint
```

**Comment by marknet15** [comment]
Cool I've done that now, so fingers crossed🤞🏻

**Comment by marknet15** [comment]
I'm going to rename `playbook.yml` to `converge.yml` also:
```
WARNING  playbook.yml was deprecated, rename it to converge.yml
```

**Comment by marknet15** [comment]
🚀 Success ! @hannseman

**Review by hannseman — APPROVED** [review]
Awesome 🎉

**Pull request merged**
